app = "p2p-video-turn"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  TURN_REALM = "p2p-video-turn"

[[services]]
  protocol = "udp"
  internal_port = 3478

  [[services.ports]]
    port = 3478

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
